export const INVALID_MIN = (n: number, name: string) => `${name + ' '}phải tối thiểu ${n} ký tự`;
export const INVALID_MAX = (n: number, name: string) => `${name + ' '}không được vượt quá ${n} ký tự`;
export const INVALID_LENGTH = (n: number, name?: string) => `${name} phải chính xác ${n} ký tự`;
export const INVALID_EMAIL = `Email không hợp lệ`;
export const INVALID_STRING = `Phải là dạng chuỗi`;
export const INVALID_NUMBER_STRING = `Chỉ bao gồm các chữ số`;
export const INVALID_NUMBER = `Giá trị phải là số`;
export const INVALID_DATE = `Ngày không hợp lệ`;
export const INVALID_UUID = `Phải có định dạng UUID`;
export const INVALID_ARRAY = `Giá trị phải là một mảng`;
export const INVALID_PASSWORD = `Mật khẩu phải có độ dài ít nhất 8 kí tự; chứa ít nhất 1 chữ hoa, 1 chữ thường và 1 số`;
export const INVALID_ENUM = (values: string[], name: string) => `${name} phải là một trong các lựa chọn: ${values.join(', ')}`;
export const INVALID_REQUIRED = 'Không được để trống';
export const INVALID_MATCH = (pattern: string, name: string) => `${name} phải có định dạng hợp lệ: ${pattern}`;
export const INVALID_MIN_LENGTH = (n: number, name: string) => `${name} phải có ít nhất ${n} ký tự`;
export const INVALID_ARRAY_MAX_SIZE = (n: number, name: string) => `${name} chỉ được thêm tối đa ${n} phần tử`;
export const INVALID_ROLE = `Role phải là admin, staff, super_admin`;
export const INVALID_BOOLEAN = `Phải là true hoặc false`;
export const INVALID_IP_4 = 'Phải định dạng theo IPv4';
export const INVALID_IP_6 = 'Phải định dạng theo IPv6';
export const INVALID_PHONE_NUMBER = 'Số điện thoại phải gồm 10 ký tự số và bắt đầu bằng 0';
export const INVALID_MONGO_ID = 'Phải có dạng objectId';
export const INVALID_OBJECT = 'Phải có dạng object';
export const INVALID_URL = 'Phải có dạng url';
