DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'CollateralType') THEN
    CREATE TYPE "CollateralType" AS ENUM ('NONE', 'IDENTITY_CARD', 'VEHICLE_OR_HIGH_VALUE', 'OTHER_ASSET');
  END IF;
END $$;

ALTER TABLE "RentalOrder"
  ADD COLUMN IF NOT EXISTS "collateralType" "CollateralType" NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "adjustedDepositTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "handoverRequiredTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "handoverAmountDue" DECIMAL(12,2) NOT NULL DEFAULT 0;
