ALTER TYPE "AssetStatus" ADD VALUE IF NOT EXISTS 'INSPECTING' AFTER 'RENTED';
ALTER TYPE "AssetStatus" ADD VALUE IF NOT EXISTS 'CLEANING' AFTER 'MAINTENANCE';
ALTER TYPE "AssetStatus" ADD VALUE IF NOT EXISTS 'TRANSFERRING' BEFORE 'LOST';
